### PR TITLE
apply globally

### PR DESCRIPTION
**Pull request by tpgunther**
Fix issue when only one line is concated. 

Apply replace function globally on the string

### CODE REVIEW

**Comment by ryanpcmcquen** [comment]
@tpgunther, thanks! Can you update the test to apply to this?

**Comment by tpgunther** [comment]
Done! Running the test I noticed an issue with the spaces before each line. I made a fix for it as well

**Comment by ryanpcmcquen** [comment]
Thanks!

**Comment by ryanpcmcquen** [comment]
It's live:
https://www.npmjs.com/package/properties-to-json

**Comment by tpgunther** [comment]
Great!

**Pull request merged**
